### ISSUE TITLE
Timecode changes after 1st minute

### ISSUE THREAD

**Issue by jamie-macleod** [mitkunz/diy_timecode_generator#3]
Less of an issue and more of a PSA so others don’t make the same mistake I did. 

The timecode changes slightly after the first minute the unit is turned on. 
This lines up with the initial signal search (Red LED) before the transition to Master (Blue LED) or Slave (Green LED). 

I need to do more testing as I lost track of exact numbers, but it’s about 00:00:00:09 to >00:00:01:00 out. 

Note - this was when using just one individual unit, so it isn’t a unit syncing issue.  
I assumed an individual unit’s time wouldn’t change so didn’t wait for initial search (Red LED) to finish. 

In practice, this means that if you turn on the unit and press record before it has initialised, your timecode will be out of sync. 
At least this will be the case for audio timecode interpreted in post, as that bases timecode on first few seconds of LTC present and doesn't adjust dynamically.

**Comment by mitkunz** [comment]
I've reduced the sync time interval from 60s to 3s, so that this change of timecode by the start of broadcasting is way earlier. This means 2 main things:
1.  you'll be able to use the devices after max. 3s of runtime (turns blue or green)
2. there will be a slight up in battery consumption, because the syncing happens more often, but this should be not that much of an issue because it needs not that much power to begin with.

I will close this issue as fixed for now.

**Comment by jamie-macleod** [comment]
Hey - just a heads up that this change has introduced another bug.

Basically, there will be glitches that last about 1 frame at (seemingly) random intervals.  The timecode will be normal, but then read something impossible, like 14:47:85:42.

I did a 3min long screen recording using the following test method:

_Test method_
DIY_timecode_generator (@25fps) into PC microphone input
Signal decoded/ displayed using TimeCode Monitor [https://timecodesync.com/monitor/]
Screen record TimeCode Monitor using OBS @25fps
Import video to Premiere Pro and examine decoded timecode frame by frame

The screenshot bellow shows an example of a timecode glitch, with each marker being an instance that one occurred over my 3 min clip.

<img width="788" alt="Timecode Glitches" src="https://github.com/mitkunz/diy_timecode_generator/assets/126464216/8d550c02-f1cb-4eef-aa0d-133e7c800238">


Changing the sync time interval from 3s back to 60s, _seems_ to at least improve things.  There are still occasional glitches, but they are far, far less frequent.
I'm going to stick with 60s, as having to wait at boot is not a bad trade off.. just something to be aware of.

Worth noting, this is different to the dropped/ skipped frame issue (https://github.com/mitkunz/diy_timecode_generator/issues/1).  This is still and issue, and doesn't appear to be linked.
